version: '2'

services:
  sonar-scanner:
    image: gcavalcante8808/sonar-scanner
    volumes:
     - /code:/code
    env_file:
     - sonar.env
# Python Common Example of extra cmd args.
#    command: -Dsonar.sources=. -Dsonar.python.coverage.reportPath=./coverage.xml -Dsonar.exclusions=**/*.js 

